# shellcheck shell=sh
# Shared release-machinery helpers. Sourced, never executed.
#
#   . "$(dirname -- "$0")/lib/release-common.sh"
#
# Before this file, `sha256_of`, the SHA256SUMS line lookup, the uname-to-target
# mapping, the ADR-0006 tier lists, the stub cosign and the selftest reporting
# harness each existed three to five times across the release scripts, and had
# already diverged in what they accepted and what they said when they refused.
# A digest helper that is correct in one copy and wrong in another is worse than
# either, because the divergence is invisible at the call site.
#
# `install.sh` deliberately does *not* source this. It is piped straight into a
# shell with no checkout to read, so it carries embedded copies of the few
# helpers it needs; `scripts/check-embedded-copies.sh` fails if those drift from
# the definitions here, the same discipline the signing pin already follows.
#
# Every function is prefixed `rc_` and every variable `RC_`/`rc_`, so a sourcing
# script can tell at a glance what came from here.

# The repository root, derived from this file's own location rather than from
# the caller's working directory: the scripts that source it are run from CI,
# from a checkout, and from inside their own throwaway fixtures.
RC_LIB_DIR=$(CDPATH='' cd -- "$(dirname -- "${RC_LIB_SELF:-$0}")" && pwd -P)
case $RC_LIB_DIR in
  */scripts/lib) RC_ROOT=$(CDPATH='' cd -- "$RC_LIB_DIR/../.." && pwd -P) ;;
  */scripts) RC_ROOT=$(CDPATH='' cd -- "$RC_LIB_DIR/.." && pwd -P) ;;
  *) RC_ROOT=$RC_LIB_DIR ;;
esac

# ---------------------------------------------------------------------------
# Digests
#
# One definition, because the two copies this replaces disagreed: both accepted
# uppercase hex from a sums file and then compared it case-sensitively against
# their own always-lowercase output, so a valid `SHA256SUMS` regenerated by a
# tool that emits uppercase (Windows `certutil`, some mirror tooling) was
# reported to the user as tampering. Digests are normalized to lowercase here,
# at the one place that produces and the one place that reads them.
# ---------------------------------------------------------------------------

# Lowercase a hex string without spawning tr on every call in the hot path.
rc_lower() {
  printf '%s' "$1" | tr 'ABCDEF' 'abcdef'
}

# SHA-256 of a file, lowercase hex. coreutils ships sha256sum; macOS ships
# shasum. Both print "<hex>  <name>", so the first field is the digest.
#
# Deliberately not `sha256sum "$1" | cut -d' ' -f1`. A pipeline's status is its
# *last* command's, so `cut` returning 0 masked a digest tool that was present
# on PATH but broken — the caller got an empty string and a success status, and
# reported it downstream as "the file hashes to  but SHA256SUMS says …", which
# is a tampering verdict for a broken toolchain. Substitution first, status
# checked, field taken afterwards.
rc_sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    rc__digest_out=$(sha256sum "$1") || rc__digest_out=''
  elif command -v shasum >/dev/null 2>&1; then
    rc__digest_out=$(shasum -a 256 "$1") || rc__digest_out=''
  else
    echo "no sha256sum or shasum on PATH — the digest check is mandatory and cannot be skipped. Install coreutils (Linux) or use the system shasum (macOS)." >&2
    return 1
  fi
  if [ -z "$rc__digest_out" ]; then
    echo "the digest tool on PATH produced no output for '$1' — it is present but not working. The digest check is mandatory and cannot be skipped; repair the installation of coreutils or shasum." >&2
    return 1
  fi
  printf '%s' "${rc__digest_out%% *}"
}

# Pull one asset's digest out of a sums file by exact name, and prove it is a
# digest before anybody compares against it.
#
# Not `sha256sum -c`, which checks every line and so fails on assets for other
# platforms that were never downloaded. The `*name` form is accepted because
# that is what `sha256sum` writes in binary mode.
#
# Prints the lowercase digest on success. On failure prints a teaching message
# to stderr and returns non-zero; the caller decides whether that is fatal.
rc_sums_digest() {
  rc__sums=$1
  rc__name=$2
  if ! rc__digest=$(awk -v want="$rc__name" \
      '$2 == want || $2 == "*" want { print $1; found = 1 } END { exit !found }' "$rc__sums"); then
    echo "$rc__sums has no entry named '$rc__name'. Either the asset was renamed after signing, or this is a different release's sums file." >&2
    return 1
  fi
  case $rc__digest in
    *[!0-9a-fA-F]* | '')
      echo "the $rc__sums entry for '$rc__name' is not a hex digest ('$rc__digest') — the file is malformed or truncated; re-download it." >&2
      return 1
      ;;
  esac
  if [ "${#rc__digest}" -ne 64 ]; then
    echo "the $rc__sums entry for '$rc__name' is ${#rc__digest} characters, not the 64 of a SHA-256 digest — the file is malformed or truncated; re-download it." >&2
    return 1
  fi
  rc_lower "$rc__digest"
}

# ---------------------------------------------------------------------------
# Platform detection
#
# One mapping, one set of refusals. The npm launcher keeps its own copy because
# it ships inside a package that has no access to this repository; the installer
# keeps its own because it is piped from curl. Both are drift-guarded.
# ---------------------------------------------------------------------------

# Sets RC_OS. Returns 1 with a teaching message on an unsupported system.
#
# Nothing in this repository calls it, and that is the point: the two consumers
# that need the mapping — install.sh and the npm launcher — cannot source this
# file, so what lives here is the *reference* their copies are compared against
# by scripts/check-embedded-copies.sh, which reads it as text. RC_OS therefore
# has no reader in shell, which is what SC2034 is reporting.
# shellcheck disable=SC2034
rc_detect_os() {
  case $(uname -s) in
    Darwin) RC_OS=darwin ;;
    Linux) RC_OS=linux ;;
    MINGW* | MSYS* | CYGWIN* | Windows_NT)
      echo "native Windows is not supported — tl's filesystem primitives are unimplemented there, so a binary would start but could not safely create or mutate task state. Use WSL2, where the Linux x86-64 build runs and is fully supported." >&2
      return 1
      ;;
    *)
      echo "unsupported operating system '$(uname -s)'. tl publishes binaries for Linux and macOS only; to use it elsewhere, build from source with Lean 4." >&2
      return 1
      ;;
  esac
}

# Sets RC_ARCH. The reference for the shipped copies, as above.
# shellcheck disable=SC2034
rc_detect_arch() {
  case $(uname -m) in
    arm64 | aarch64) RC_ARCH=arm64 ;;
    x86_64 | amd64) RC_ARCH=x64 ;;
    *)
      echo "unsupported CPU architecture '$(uname -m)'. tl publishes arm64 and x86-64 binaries; to use it elsewhere, build from source with Lean 4." >&2
      return 1
      ;;
  esac
}

# There is deliberately no `rc_detect_target` composing the two above. One
# existed and nothing called it: the consumers that need a target string are
# install.sh and the npm launcher, and both carry their own copies precisely
# because neither can source this file. A convenience wrapper with no caller is
# a third definition of the mapping waiting to drift from the two that ship.

# ---------------------------------------------------------------------------
# Targets and ADR-0006 support tiers, from release/targets.json
#
# The tier split decides whether a missing binary is a warning or a refusal, and
# it decided that independently in npm-pack.sh, gen-homebrew-formula.sh and the
# release workflow. One source now, so "Supported" cannot mean three things.
# ---------------------------------------------------------------------------

RC_TARGETS_FILE=${RC_TARGETS_FILE:-"$RC_ROOT/release/targets.json"}

# rc_targets [tier] — space-separated target names, in file order. With no
# argument, every target; with `supported` or `best-effort`, that tier only.
rc_targets() {
  rc__tier=${1-}
  [ -f "$RC_TARGETS_FILE" ] || {
    echo "$RC_TARGETS_FILE not found — it is the one place the distributed targets and their ADR-0006 tiers are recorded, and every consumer reads it rather than repeating the list." >&2
    return 1
  }
  command -v python3 >/dev/null 2>&1 || {
    echo "python3 not found — it reads release/targets.json. A text scrape would silently return an empty target list, which reads as 'nothing to publish' rather than as a broken tool." >&2
    return 1
  }
  python3 -c '
import json, sys
path, tier = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as handle:
    data = json.load(handle)
names = [t["target"] for t in data["targets"] if not tier or t["tier"] == tier]
if not names:
    sys.exit(f"release/targets.json lists no targets for tier {tier!r}")
print(" ".join(names))
' "$RC_TARGETS_FILE" "$rc__tier"
}

RC_PLAN_FILE=${RC_PLAN_FILE:-"$RC_ROOT/release/plan.json"}

# rc_channel_state <channel> — print `enabled`, or `deferred <version>`.
# Returns non-zero, having explained itself on stderr, when the plan cannot be
# read; the caller must not treat that as "off". A channel this release defers
# needs none of its prerequisites, and a channel nobody could ask about is a
# different answer from one deliberately switched off.
rc_channel_state() {
  [ -f "$RC_PLAN_FILE" ] || {
    echo "$RC_PLAN_FILE not found — it is the one place the channels a release publishes through are recorded, and every consumer reads it rather than assuming." >&2
    return 1
  }
  command -v python3 >/dev/null 2>&1 || {
    echo "python3 not found — it reads release/plan.json. A text scrape would silently report a channel as off, which reads as 'deliberately deferred' rather than as a broken tool." >&2
    return 1
  }
  python3 -c '
import json, sys
path, channel = sys.argv[1], sys.argv[2]
try:
    with open(path, encoding="utf-8") as handle:
        data = json.load(handle)
    rows = [row for row in data["channels"] if row.get("channel") == channel]
except (OSError, ValueError, KeyError, TypeError) as error:
    sys.exit(f"{path} could not be read as a release plan ({error}).")
if len(rows) != 1:
    sys.exit(f"{path} has {len(rows)} rows for the {channel!r} channel; it must have exactly one.")
row = rows[0]
if not isinstance(row.get("enabled"), bool):
    sys.exit(f"{path} does not say whether the {channel!r} channel is enabled.")
if row["enabled"]:
    print("enabled")
else:
    planned = row.get("plannedFor")
    if not isinstance(planned, str) or not planned:
        sys.exit(f"{path} defers the {channel!r} channel without naming the release it is planned for.")
    print(f"deferred {planned}")
' "$RC_PLAN_FILE" "$1"
}

# rc_target_tier <target> — `supported`, `best-effort`, or a refusal.
rc_target_tier() {
  python3 -c '
import json, sys
path, want = sys.argv[1], sys.argv[2]
with open(path, encoding="utf-8") as handle:
    data = json.load(handle)
for entry in data["targets"]:
    if entry["target"] == want:
        print(entry["tier"])
        break
else:
    sys.exit(f"{want!r} is not a target in release/targets.json; add it there rather than special-casing it here")
' "$RC_TARGETS_FILE" "$1"
}

# rc_target_is_required <target> — true for the release-blocking tier.
rc_target_is_required() {
  [ "$(rc_target_tier "$1")" = supported ]
}

# ---------------------------------------------------------------------------
# Selftest harness
#
# Every release script grew its own `note`, and three of them grew more than
# one reporting style. Worse, the common shape
#
#     ( cd … && some_command >/dev/null 2>&1 )
#     note $? "the thing works"
#
# cannot fail: under `set -e` the script has already exited by the time `note`
# runs, so the row prints `ok` on success and nothing at all on failure — no
# FAIL line, no captured diagnostic, no summary. Five such rows existed. The
# helpers below take the command instead of its status, so the status is
# observed rather than inferred, and the command's output is kept and shown.
# ---------------------------------------------------------------------------

# rc_selftest_begin <label> [scratch-dir] — call once, after setting up a temp
# dir. The scratch dir is where captured stdout and stderr land; passing it here
# rather than having each caller assign RC_OUT/RC_ERR keeps those variables
# owned by the one file that reads them. Shellcheck flagged ten assignments as
# unused for exactly that reason — it cannot see through the `.` into this
# library — and silencing ten directives would have been the wrong repair for
# a real smell.
rc_selftest_begin() {
  RC_SELFTEST_LABEL=$1
  RC_FAILURES=0
  rc_capture_into "${2:-${TMPDIR:-/tmp}}"
  echo "$RC_SELFTEST_LABEL --selftest:"
}

# rc_capture_into <dir> — where `rc_run` puts the captured stdout and stderr.
# Non-selftest callers that use `rc_run`/`$RC_OUT`/`$RC_ERR` call this; under
# `set -u` an unset RC_OUT is an immediate failure, so it is not optional.
rc_capture_into() {
  RC_OUT="$1/rc-out.$$"
  RC_ERR="$1/rc-err.$$"
}

# rc_note <status> <name> — record an already-observed status.
rc_note() {
  if [ "$1" -eq 0 ]; then
    echo "  ok   $2"
  else
    echo "  FAIL $2" >&2
    RC_FAILURES=$((RC_FAILURES + 1))
  fi
}

# rc_run <cmd>... — run a command with errexit neutralized, capturing stdout in
# $RC_OUT and stderr in $RC_ERR and leaving the status in $RC_STATUS. Always
# returns 0, so a caller under `set -e` survives to inspect the outcome.
rc_run() {
  RC_STATUS=0
  "$@" >"$RC_OUT" 2>"$RC_ERR" || RC_STATUS=$?
  return 0
}

# rc_expect_status <want> <name> <cmd>... — the workhorse. Runs the command,
# compares its status, and on a mismatch prints the captured stderr, which is
# the part the discarded-output pattern used to throw away.
rc_expect_status() {
  rc__want=$1
  rc__name=$2
  shift 2
  rc_run "$@"
  if [ "$RC_STATUS" -eq "$rc__want" ]; then
    echo "  ok   $rc__name (exit $RC_STATUS)"
    return 0
  fi
  echo "  FAIL $rc__name: expected exit $rc__want, got $RC_STATUS" >&2
  sed 's/^/    /' "$RC_ERR" >&2
  RC_FAILURES=$((RC_FAILURES + 1))
}

# rc_expect_output <want-status> <substring> <name> <cmd>... — status *and* a
# substring of the combined output, for the refusals whose message is the point.
rc_expect_output() {
  rc__want=$1
  rc__needle=$2
  rc__name=$3
  shift 3
  rc_run "$@"
  rc__matched=0
  grep -q -- "$rc__needle" "$RC_ERR" "$RC_OUT" && rc__matched=1
  if [ "$RC_STATUS" -eq "$rc__want" ] && [ "$rc__matched" -eq 1 ]; then
    echo "  ok   $rc__name (exit $RC_STATUS)"
    return 0
  fi
  # Which half failed, not just that one did. A row whose status is right and
  # whose message is wrong is the common case — the code took some *other*
  # refusal path — and reporting only the status sends the reader looking at
  # the exit code, which was never the problem.
  if [ "$RC_STATUS" -ne "$rc__want" ]; then
    echo "  FAIL $rc__name: expected exit $rc__want, got $RC_STATUS" >&2
  else
    echo "  FAIL $rc__name: exit $RC_STATUS was expected, but no output matched '$rc__needle' — the command refused for some other reason" >&2
  fi
  sed 's/^/    /' "$RC_ERR" >&2
  RC_FAILURES=$((RC_FAILURES + 1))
}

# rc_selftest_end <remedy> — exit 1 with a count when anything failed.
rc_selftest_end() {
  if [ "$RC_FAILURES" -ne 0 ]; then
    echo "$RC_SELFTEST_LABEL: --selftest found $RC_FAILURES broken case(s). $1" >&2
    exit 1
  fi
  echo "$RC_SELFTEST_LABEL: --selftest passed"
  exit 0
}

# ---------------------------------------------------------------------------
# The stub cosign
#
# Both verifier selftests fabricate one, and the two copies had already diverged
# in what they assert. The stub's job is not to imitate cosign: it is to prove
# that the caller handed cosign the *pinned* issuer and expression, byte for
# byte, and never a transparency-log bypass. A stub that ignored its arguments
# would stay green while its caller passed a mangled expression — the failure
# that reaches users as "every genuine release is rejected".
#
# rc_write_stub_cosign <bin-dir> <identity-pin> <log-dir>
#
# <identity-pin> is release/identity.pin — the two inert lines a verifier
# actually reads, not release/identity.json. The stub compares what its caller
# passed against the same file the caller was supposed to read, so a verifier
# that quietly used a different pin fails here. Reading it the same way the
# verifier does (one descriptor, `IFS= read -r`) is also what keeps `python3`
# off the selftest path, which is itself part of the release policy.
#   COSIGN_STUB_VERDICT=ok|bad|broken   the verdict for every call
#   COSIGN_STUB_FAIL_ON=<basename>      fail one named blob only
# Writes <log-dir>/cosign-argv and <log-dir>/cosign-blobs.
# ---------------------------------------------------------------------------
rc_write_stub_cosign() {
  rc__bin=$1
  rc__pin=$2
  rc__log=$3
  mkdir -p "$rc__bin" "$rc__log"
  cat > "$rc__bin/cosign" <<STUB
#!/bin/sh
pin='$rc__pin'
log='$rc__log'
printf '%s\n' "\$*" >> "\$log/cosign-argv"
want_issuer=''
want_identity=''
{
  IFS= read -r want_issuer || true
  IFS= read -r want_identity || true
} < "\$pin"
blob=''
got_issuer=''
got_identity=''
got_bundle=''
seen_verify=0
while [ \$# -gt 0 ]; do
  case \$1 in
    verify-blob) seen_verify=1; shift ;;
    --certificate-oidc-issuer) got_issuer=\$2; shift 2 ;;
    --certificate-identity-regexp) got_identity=\$2; shift 2 ;;
    --bundle) got_bundle=\$2; shift 2 ;;
    --insecure-ignore-tlog*)
      echo "stub cosign: called with \$1 — the transparency-log check must never be bypassed" >&2
      exit 90
      ;;
    -*) shift ;;
    *) [ -n "\$blob" ] || blob=\$1; shift ;;
  esac
done
[ "\$seen_verify" -eq 1 ] || { echo "stub cosign: not a verify-blob call" >&2; exit 95; }
[ "\$got_issuer" = "\$want_issuer" ] || {
  echo "stub cosign: issuer '\$got_issuer' is not the pinned '\$want_issuer'" >&2
  exit 91
}
[ "\$got_identity" = "\$want_identity" ] || {
  echo "stub cosign: identity expression '\$got_identity' is not the pinned '\$want_identity'" >&2
  exit 92
}
[ -n "\$got_bundle" ] || { echo "stub cosign: no --bundle was passed" >&2; exit 93; }
[ -f "\$got_bundle" ] || { echo "stub cosign: bundle '\$got_bundle' does not exist" >&2; exit 94; }
printf '%s\n' "\${blob##*/}" >> "\$log/cosign-blobs"
if [ -n "\${COSIGN_STUB_FAIL_ON:-}" ] && [ "\${blob##*/}" = "\$COSIGN_STUB_FAIL_ON" ]; then
  echo "error: no matching signatures: none of the expected identities matched what was in the certificate" >&2
  exit 1
fi
case "\${COSIGN_STUB_VERDICT:-ok}" in
  ok) ;;
  bad)
    echo "error: no matching signatures: none of the expected identities matched what was in the certificate" >&2
    exit 1
    ;;
  broken)
    echo "error: fetching trust root: Get \"https://tuf-repo-cdn.sigstore.dev/\": dial tcp: lookup failed" >&2
    exit 1
    ;;
esac
echo "Verified OK"
exit 0
STUB
  chmod +x "$rc__bin/cosign"
}

# rc_write_stub_uname <dir> <uname-s> <uname-m> — a `uname` first on PATH, so
# the platform branches are driven through the real code rather than inspected.
rc_write_stub_uname() {
  mkdir -p "$1"
  cat > "$1/uname" <<UNAME
#!/bin/sh
case "\$1" in
  -s) echo "$2" ;;
  -m) echo "$3" ;;
  *) echo "$2" ;;
esac
UNAME
  chmod +x "$1/uname"
}
