/-
The release SBOM, in SPDX 2.3 JSON.

ADR-0006 requires every binary release to carry an SBOM and the full link-time
dependency audit. The audit is per-target and produced by the build legs — they
are the only place the actual binary exists. This is the repository-level half:
what went into the build, taken from the files that already fix it.

  lean-toolchain       the compiler, and with it the Lean runtime, the
                       statically linked GMP and libuv, and the rest of the
                       bundled link set
  lake-manifest.json   every Lake dependency, pinned to an immutable commit

Deriving the document from those two files rather than from a maintained list
is the point: a list could disagree with the build, and nothing would say so.
For the same reason it is not produced by a third-party scanner: none of them
understands Lake, and one that silently found nothing would emit a confident
empty document that still reads as evidence. Every input is refused when it is
missing, unreadable, or not what it claims to be.

The bytes are a function of the release and of nothing else: no generation
timestamp, no random document id, and `release/Json.lean`'s deterministic
renderer. The SBOM is hashed into `SHA256SUMS` and signed, so two independent
generations for one release have to agree exactly.

What it refuses, beyond the inputs simply being readable. Each of these is a
claim the document makes, checked rather than assumed — and since the document
is signed and published as evidence of what a release was built from, a field
that merely holds text is worse than one that declines to say:

- a manifest belonging to another Lake package. The path to one is an argument
  rather than something this command derives, so being handed another
  checkout's is a mistake it can make;
- a dependency Lake did not resolve from git, which this document has no way to
  describe and would otherwise render as a git package that does not exist;
- a `rev` that is not a full 40-character object id, which is what ADR-0009
  means by an immutable pin; a branch name would describe a build nobody can
  reconstruct;
- a `url` that is empty, not a string, or not a location anything could fetch
  from — it is composed into `git+<url>@<rev>`, which a reader resolves;
- two packages whose names map to the same SPDX identifier, because identifiers
  are unique within a document and a name is mapped into a restricted character
  class on the way in, so distinct names can collide there;
- a `lean-toolchain` of more than one line, or one naming a channel rather than
  a pin: `stable` resolves to whatever it points at today, and this field is
  read as the compiler the release was built with.
-/
import release.Command
import release.Model

namespace Release

open Lean (Json)

/-! ## The constants this document is written from

Hard-coded here rather than read from `release/identity.json`, deliberately:
the SBOM is derived from the files that fix the *build*, and adding a fourth
input would add a fourth way for the document to be unavailable. The repository
name appearing in two files is guarded by the release-identity check, not by
threading it through here. -/

private def repositoryUrl : String := "https://github.com/DmitryKorolev/tl"

private def organization : String := "Organization: DmitryKorolev"

/-- The tool line in `creationInfo.creators`. Names the command a reader can
    run to regenerate the document, which is the only reason the field is worth
    carrying. -/
private def toolCreator : String := "Tool: tlrelease sbom"

/-- SPDX requires `created`, and this document deliberately does not carry the
    moment it was generated: it is regenerated by anyone rebuilding the same
    release, and a field that changed per run would make two correct SBOMs for
    one release differ. The field therefore carries the release, through the
    rest of the document, and the epoch here says "not stamped" rather than
    claiming a time. -/
private def fixedCreationTime : String := "1970-01-01T00:00:00Z"

private def creationComment : String :=
  "Generated from lean-toolchain and lake-manifest.json, the files that fix this build. The `created` field is fixed rather than stamped so the document is a function of the release and two independent generations agree. The per-target link-time audit ships alongside as link-audit-<target>.txt."

/-- SPDX's "nothing is asserted here", which is a statement rather than a gap:
    it is what distinguishes a field this generator declined to fill from one it
    forgot. -/
private def noAssertion : String := "NOASSERTION"

/-! ## One package in the document -/

/-- A package row, in the shape SPDX describes it. `comment` is optional because
    the subject of the document has nothing to explain about itself and every
    dependency does. -/
structure SbomPackage where
  identifier : String
  name : String
  versionInfo : String
  downloadLocation : String
  licenseConcluded : String
  licenseDeclared : String
  supplier : String
  comment : Option String
  deriving Repr, Inhabited

/-- An SPDX identifier must be unique within the document and must match
    `[A-Za-z0-9.-]`. Lake package names are already in that class today; the
    mapping is explicit rather than assumed, and `Sbom.of` refuses the collision
    it can produce. -/
def spdxIdentifier (name : String) : String :=
  let admissible (c : Char) : Bool :=
    ('A' ≤ c && c ≤ 'Z') || ('a' ≤ c && c ≤ 'z') || ('0' ≤ c && c ≤ '9')
      || c == '.' || c == '-'
  "SPDXRef-Package-" ++ name.map fun c => if admissible c then c else '-'

/-- The subject of the document: the thing being released. -/
private def subjectPackage (version : Version) : SbomPackage := {
  identifier := "SPDXRef-Package-tl"
  name := "tl"
  versionInfo := version.render
  downloadLocation := repositoryUrl
  licenseConcluded := "Apache-2.0"
  licenseDeclared := "Apache-2.0"
  supplier := organization
  comment := none }

/-- The toolchain is a dependency of the artifact in every sense that matters
    here: it supplies the Lean runtime and, through it, the statically linked
    GMP that the ADR-0006 licensing section is about. -/
private def toolchainPackage (toolchain : String) : SbomPackage := {
  identifier := "SPDXRef-Package-lean-toolchain"
  name := "lean4"
  versionInfo := toolchain
  downloadLocation := "https://github.com/leanprover/lean4"
  licenseConcluded := "Apache-2.0"
  licenseDeclared := "Apache-2.0"
  supplier := "Organization: Lean FRO"
  comment := some "Supplies the Lean runtime linked into every tl binary, and with it the statically linked GMP (LGPL-3.0-or-later, elected over the GPL-2.0 option) and libuv (MIT). See the licensing section of ADR-0006 and THIRD-PARTY-LICENSES." }

private def gmpPackage : SbomPackage := {
  identifier := "SPDXRef-Package-gmp"
  name := "gmp"
  versionInfo := noAssertion
  downloadLocation := "https://gmplib.org/"
  licenseConcluded := "LGPL-3.0-or-later"
  licenseDeclared := "LGPL-3.0-or-later OR GPL-2.0-or-later"
  supplier := noAssertion
  comment := some "Statically linked via the Lean toolchain, not vendored by this project. tl elects the LGPL-3.0 option; the section 4 relink obligation is met by tl remaining open source with a pinned build system (ADR-0006)." }

private def libuvPackage : SbomPackage := {
  identifier := "SPDXRef-Package-libuv"
  name := "libuv"
  versionInfo := noAssertion
  downloadLocation := "https://github.com/libuv/libuv"
  licenseConcluded := "MIT"
  licenseDeclared := "MIT"
  supplier := noAssertion
  comment := some "Statically linked into every Lean binary and omitted from Lean's own bundled LICENSES file, so tl's notice adds the entry itself." }

/-- The permissive allowlist is enforced by `Tests/CliTests.lean` against each
    package's LICENSE on disk. Concluding a license here without re-deriving it
    would be a second, weaker copy of that gate, so every Lake row asserts
    nothing and says where the classification actually happens. -/
private def lakeDependencyComment : String :=
  "Lake dependency, pinned to an immutable commit (ADR-0009). Its license is classified fail-closed against the permissive allowlist by Tests/CliTests.lean and recorded in THIRD-PARTY-LICENSES."

/-! ## What `lake-manifest.json` says -/

/-- One Lake dependency, as this document needs it: a name, the immutable commit
    it is pinned to, and where it came from.

    `url` is an `Option` because a manifest may decline to say — and declining is
    different from saying nothing intelligible, which is refused on the way in. -/
structure LakeDependency where
  name : String
  revision : Commit
  url : Option String
  deriving Repr

def LakeDependency.toPackage (dependency : LakeDependency) : SbomPackage := {
  identifier := spdxIdentifier dependency.name
  name := dependency.name
  versionInfo := dependency.revision.hex
  downloadLocation :=
    match dependency.url with
    | none => noAssertion
    | some url => s!"git+{url}@{dependency.revision.hex}"
  licenseConcluded := noAssertion
  licenseDeclared := noAssertion
  supplier := noAssertion
  comment := some lakeDependencyComment }

/-- A download location a consumer could resolve: one scheme, and nothing in it
    that a URL cannot carry. It is composed into `git+<url>@<rev>`, so free text
    here becomes a location that reads as one and resolves to nothing. -/
private def resolvableLocation (text : String) : Bool :=
  (text.splitOn "://").length == 2
    && !text.any fun c => c.toNat < 0x21 || c.toNat > 0x7e

private def parseDependency (cursor : Cursor) (value : Json) : Except String LakeDependency := do
  let name ← nonEmptyStringField cursor value "name"
  -- Every row is described below as a git package pinned to a commit. Lake
  -- writes the kind it resolved, and a kind this document has no way to
  -- describe is refused rather than described as something else: a `path`
  -- dependency rendered as `git+…` would name a repository nobody can fetch.
  let kind ← nonEmptyStringField cursor value "type"
  if kind != "git" then
    (cursor.at "type").fail s!"is '{kind}', and this document describes each Lake dependency as a git package pinned to an immutable commit. A dependency of another kind is not something it can describe, so it is refused rather than recorded as a git package that does not exist. Vendor the dependency or depend on it by git before cutting a release."
  let revisionText ← nonEmptyStringField cursor value "rev"
  -- ADR-0009 pins every dependency to an immutable commit, so an entry without
  -- one is either a manifest this generator does not understand or a pin that
  -- is not immutable.
  let revision ← (Commit.parse s!"{(cursor.at "rev").render} (the '{name}' dependency)"
      revisionText).mapError fun message =>
    s!"{message} ADR-0009 pins every Lake dependency to an immutable commit, and this SBOM records what the release was actually built from; regenerate lake-manifest.json with `lake update` rather than editing the pin by hand."
  let url ← match field? value "url" with
    | none => pure none
    | some found => do
        let text ← asString (cursor.at "url") found
        if text.isEmpty then
          (cursor.at "url").fail "is empty. An empty download location is not the same as declining to give one: omit the field, or write NOASSERTION, so the document says which it means."
        -- The sentinel is carried rather than composed into a location: a
        -- manifest that already declines to name a URL must not acquire one
        -- reading `git+NOASSERTION@<rev>`.
        else if text == noAssertion then pure none
        else if !resolvableLocation text then
          (cursor.at "url").fail s!"is '{text}', which is not a location anything could fetch from. It is composed into 'git+<url>@<rev>' in a document that is signed and published as evidence of what this release was built from, so text that merely occupies the field would be worse than the NOASSERTION that declines it."
        else pure (some text)
  return { name, revision, url }

/-- The Lake package this document is about. `lake-manifest.json` names the
    package it belongs to, and the path to one is an argument rather than
    something this command derives, so a manifest from another checkout is a
    reachable mistake and not a hypothesis. -/
private def productPackage : String := "tl"

/-- Every Lake dependency, in manifest order. Order is part of the document:
    a consumer that re-derived it would produce different bytes for the same
    release. -/
def parseLakeManifest (document : String) (text : String) :
    Except String (List LakeDependency) := do
  let cursor : Cursor := { document }
  let root ← parseDocument cursor text
  let package ← nonEmptyStringField cursor root "name"
  if package != productPackage then
    cursor.fail s!"describes the Lake package '{package}', and this document is about '{productPackage}'. That is another project's manifest: pass the one from the checkout being released, or this release would be published describing a dependency set it was not built from."
  let (inner, found) ← field cursor root "packages"
  let rows ← asArray inner found
  let dependencies ← rows.mapM fun (rowCursor, row) => parseDependency rowCursor row
  if dependencies.isEmpty then
    inner.fail "lists no packages, which cannot be right — every build of tl resolves at least one Lake dependency. An empty SBOM would read as 'nothing ships' rather than as a broken generator, so it is refused; regenerate the manifest with `lake update` against this commit."
  return dependencies

/-! ## The version

The toolchain is parsed by `parseToolchain` in `release/Model.lean`: three
commands read `lean-toolchain` now, and a second reading of it would be a
second opinion about what this release was built with. -/

/-- The release being described, which is the bare version and never the tag.
    The document composes the tag form itself for its namespace, so accepting
    one here would produce `vv0.1.0` in a field nothing would later notice. -/
def parseReleaseVersion (text : String) : Except String Version :=
  if text.startsWith "v" then
    .error s!"the release version: '{text}' carries a leading 'v'. Pass the bare version — this document composes the tag form itself, so a tag here would name its namespace 'v{text}'."
  else Version.parse "the release version" text

/-! ## The document -/

/-- What the document says: one subject, and everything it depends on.

    The subject is a field rather than the head of a list, so "the document
    describes tl, and every other package is a dependency of it" is structural
    rather than a matter of which row comes first — the relationships are
    derived from it, and a positional reading of them holds only until someone
    inserts a row.

    Private constructor: `of` is the only way in, and it refuses a package set
    SPDX could not express. -/
structure Sbom where
  private mk ::
  version : Version
  subject : SbomPackage
  dependencies : List SbomPackage

def Sbom.packages (sbom : Sbom) : List SbomPackage := sbom.subject :: sbom.dependencies

/-- The first identifier two packages share, with both their names. Adjacent
    pairs of a sorted list, so the work is one sort rather than a scan of the
    whole list per package. -/
private def sharedIdentifier : List (String × String) → Option (String × String × String)
  | [] => none
  | [_] => none
  | (identifier, name) :: rest@((nextIdentifier, nextName) :: _) =>
      if identifier == nextIdentifier then some (identifier, name, nextName)
      else sharedIdentifier rest

/-- SPDX identifiers are unique within a document, and `spdxIdentifier` maps a
    name into a restricted character class on the way in — so two distinct
    names can arrive at one identifier. A document with a repeated identifier
    describes neither package: every relationship naming it is ambiguous. -/
private def distinctIdentifiers (packages : List SbomPackage) : Except String Unit :=
  let ordered := (packages.map fun package => (package.identifier, package.name)).mergeSort
    (fun left right => left.1 ≤ right.1)
  match sharedIdentifier ordered with
  | none => .ok ()
  | some (identifier, first, second) =>
      .error s!"the SPDX identifier '{identifier}' describes both '{first}' and '{second}'. Identifiers are unique within a document, and a package name is mapped into the identifier character class on the way in, so two distinct names can collide there. Rename the dependency, or drop the duplicate row from lake-manifest.json."

/-- Assemble the document, refusing a package set SPDX could not express. -/
def Sbom.of (version : Version) (toolchain : String) (dependencies : List LakeDependency) :
    Except String Sbom := do
  let sbom : Sbom :=
    ⟨version, subjectPackage version,
      [toolchainPackage toolchain, gmpPackage, libuvPackage]
        ++ dependencies.map (·.toPackage)⟩
  distinctIdentifiers sbom.packages
  return sbom

private def packageJson (package : SbomPackage) : Json :=
  Json.mkObj ([
    ("SPDXID", Json.str package.identifier),
    ("name", Json.str package.name),
    ("versionInfo", Json.str package.versionInfo),
    ("downloadLocation", Json.str package.downloadLocation),
    -- This document describes what went into the build, not the file inventory
    -- of each dependency, so no package claims to have been analysed.
    ("filesAnalyzed", Json.bool false),
    ("licenseConcluded", Json.str package.licenseConcluded),
    ("licenseDeclared", Json.str package.licenseDeclared),
    ("copyrightText", Json.str noAssertion),
    ("supplier", Json.str package.supplier)] ++
    match package.comment with
    | none => []
    | some comment => [("comment", Json.str comment)])

private def relationshipJson (element relationship related : String) : Json :=
  Json.mkObj [
    ("spdxElementId", Json.str element),
    ("relationshipType", Json.str relationship),
    ("relatedSpdxElement", Json.str related)]

/-- The document describes its subject, and its subject depends on everything
    else. Derived from the structure rather than from list positions. -/
def Sbom.relationships (sbom : Sbom) : List Json :=
  relationshipJson "SPDXRef-DOCUMENT" "DESCRIBES" sbom.subject.identifier ::
    sbom.dependencies.map fun package =>
      relationshipJson sbom.subject.identifier "DEPENDS_ON" package.identifier

def Sbom.toJson (sbom : Sbom) : Json :=
  Json.mkObj [
    ("spdxVersion", Json.str "SPDX-2.3"),
    ("dataLicense", Json.str "CC0-1.0"),
    ("SPDXID", Json.str "SPDXRef-DOCUMENT"),
    ("name", Json.str ("tl-" ++ sbom.version.render)),
    ("documentNamespace", Json.str s!"{repositoryUrl}/spdx/{sbom.version.tag}"),
    ("creationInfo", Json.mkObj [
      ("created", Json.str fixedCreationTime),
      ("creators", Json.arr #[Json.str toolCreator, Json.str organization]),
      ("comment", Json.str creationComment)]),
    ("packages", Json.arr (sbom.packages.map packageJson).toArray),
    ("relationships", Json.arr sbom.relationships.toArray)]

/-- The bytes to write: sorted keys, two-space indent, trailing newline. -/
def renderSbom (sbom : Sbom) : Except String String := render sbom.toJson

/-! ## From the inputs to the document

The three files as text, each with the path it came from so a refusal names the
file the operator has to fix. Kept separate from the command so every refusal
below is reachable from a test without a filesystem. -/

structure SbomInputs where
  version : String
  toolchainDocument : String
  toolchainText : String
  manifestDocument : String
  manifestText : String
  deriving Inhabited

def sbomOfInputs (inputs : SbomInputs) : Except String Sbom := do
  let version ← parseReleaseVersion inputs.version
  let toolchain ← parseToolchain inputs.toolchainDocument inputs.toolchainText
  let dependencies ← parseLakeManifest inputs.manifestDocument inputs.manifestText
  Sbom.of version toolchain dependencies

/-- Inputs to bytes, which is what the command does either side of its I/O. -/
def renderSbomOfInputs (inputs : SbomInputs) : Except String String :=
  sbomOfInputs inputs >>= renderSbom

/-- What a missing input means, said once. A generator that carried on without
    one would describe a smaller release than the one being published, and
    nothing downstream could tell that from a release that really is smaller. -/
private def missingInputRemedy : String :=
  "The SBOM is derived from the files that fix the build, so without this one the document would understate what ships. Run it from the checkout being released, with paths relative to it."

private def sbomCommand : Command :=
  positionalCommand "sbom" "<version> <lean-toolchain> <lake-manifest.json> <output.spdx.json>"
    "Write the release's SPDX 2.3 SBOM, from the files that fix the build."
    ["0.1.0", "lean-toolchain", "lake-manifest.json", "dist/tl.spdx.json"] 4 fun args => do
    match args with
    | [versionText, toolchainPath, manifestPath, outputPath] =>
        -- The version first: it is the argument an operator types, so a
        -- mistake in it should not be reported as whichever file happened to
        -- be unreadable as well.
        match parseReleaseVersion versionText with
        | .error message => refuse s!"tlrelease sbom: {message}"
        | .ok version =>
            match ← readTextFile toolchainPath, ← readTextFile manifestPath with
            | .error message, _ => refuse s!"tlrelease sbom: {message}. {missingInputRemedy}"
            | _, .error message => refuse s!"tlrelease sbom: {message}. {missingInputRemedy}"
            | .ok toolchainText, .ok manifestText =>
                let assembled := do
                  let toolchain ← parseToolchain toolchainPath toolchainText
                  let dependencies ← parseLakeManifest manifestPath manifestText
                  Sbom.of version toolchain dependencies
                match assembled with
                | .error message => refuse s!"tlrelease sbom: {message}"
                | .ok sbom =>
                    match renderSbom sbom with
                    | .error message => refuse s!"tlrelease sbom: {message}"
                    | .ok document =>
                        match ← writeFileAtomically outputPath document with
                        | .error message => refuse s!"tlrelease sbom: {message}"
                        | .ok () =>
                            IO.println s!"tlrelease sbom: wrote {outputPath} — {sbom.packages.length} packages for tl {sbom.version.render}"
                            return 0
    | _ => wrongArity

def sbomCommands : List Command := [sbomCommand]

end Release
