/- Reviewed workflow capabilities and argv. These values are independent of the
   workflow being checked; a workflow edit cannot grant itself a new capability. -/
import release.WorkflowPolicy
namespace Release.WorkflowPolicy

def releaseContract : Contract := {
  header := [("concurrency", "\n  group: release-${{ github.ref }}\n  cancel-in-progress: false"),
 ("defaults", "\n  run:\n    shell: bash"),
 ("env",
  "\n  GLIBC_FLOOR_IMAGE: \"ubuntu@sha256:152dc042452c496007f07ca9127571cb9c29697f42acbfad72324b2bb2e43c98\"\n  GLIBC_FLOOR: \"2.27\"\n  ELAN_VERSION: \"v4.2.3\""),
 ("name", "Release"),
 ("on",
  "\n  push:\n    tags:\n      - \"v[0-9]+.[0-9]+.[0-9]+\"\n      - \"v[0-9]+.[0-9]+.[0-9]+-*\"\n  workflow_dispatch:\n    inputs:\n      handoff_only:\n        description: Run the gates and capability-free tool handoff without the release matrix\n        type: boolean\n        default: false"),
 ("permissions", "\n  contents: read")]
  jobs := [
{ name := "gates",
  fields := [("outputs",
              "\n      npm: ${{ steps.plan.outputs.npm }}\n      homebrew: ${{ steps.plan.outputs.homebrew }}\n      releaseToolFileSetHash: ${{ steps.tool_file_set_hash.outputs.fileSetHash }}"),
             ("runs-on", "ubuntu-latest"),
             ("timeout-minutes", "90")],
  closedSteps := false,
  steps := [{ name := "typed release policy",
              fields := [("if", "github.ref_type != 'tag'")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./.lake/build/bin/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "policy",
                                       Release.WorkflowPolicy.Argument.literal "--profile",
                                       Release.WorkflowPolicy.Argument.literal "release",
                                       Release.WorkflowPolicy.Argument.literal "--strict"] } },
            { name := "typed release policy on a tag",
              fields := [("if", "github.ref_type == 'tag'")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./.lake/build/bin/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "policy",
                                       Release.WorkflowPolicy.Argument.literal "--profile",
                                       Release.WorkflowPolicy.Argument.literal "release",
                                       Release.WorkflowPolicy.Argument.literal "--strict",
                                       Release.WorkflowPolicy.Argument.literal "--tag"] } },
            { name := "which channels this release publishes through",
              fields := [("id", "plan")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./.lake/build/bin/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "workflow-plan",
                                       Release.WorkflowPolicy.Argument.literal "--plan",
                                       Release.WorkflowPolicy.Argument.literal "release/plan.json",
                                       Release.WorkflowPolicy.Argument.literal "--output",
                                       Release.WorkflowPolicy.Argument.environment "GITHUB_OUTPUT"] } },
            { name := "stage the release tool",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "install",
                         arguments := [Release.WorkflowPolicy.Argument.literal "-D",
                                       Release.WorkflowPolicy.Argument.literal "-m",
                                       Release.WorkflowPolicy.Argument.literal "0755",
                                       Release.WorkflowPolicy.Argument.literal ".lake/build/bin/tlrelease",
                                       Release.WorkflowPolicy.Argument.literal "release-tool/tlrelease"] } },
            { name := "hash the staged release tool file set",
              fields := [("env", "\n          RELEASE_TOOL_FILE_SET_HASH: ${{ hashFiles('release-tool/tlrelease') }}"),
                         ("id", "tool_file_set_hash")],
              run := Release.WorkflowPolicy.Run.fileSetHash },
            { name := "upload the release tool for the signing job",
              fields := [("uses", "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"),
                         ("with",
                          "\n          name: release-tool\n          path: release-tool/tlrelease\n          if-no-files-found: error\n          retention-days: 7")],
              run := Release.WorkflowPolicy.Run.none }],
  references := ["steps.plan.outputs.homebrew", "steps.plan.outputs.npm",
                 "steps.tool_file_set_hash.outputs.fileSetHash"] },
{ name := "handoff-rehearsal",
  fields := [("if", "github.event_name == 'workflow_dispatch' && github.ref_type == 'branch'"),
             ("needs", "[gates]"),
             ("permissions", "{}"),
             ("runs-on", "ubuntu-latest"),
             ("timeout-minutes", "5")],
  closedSteps := true,
  steps := [{ name := "download the release tool",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with", "\n          name: release-tool\n          path: tool")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "refuse a missing or changed release tool",
              fields := [("if",
                          "needs.gates.outputs.releaseToolFileSetHash == '' || hashFiles('tool/tlrelease') == '' || needs.gates.outputs.releaseToolFileSetHash != hashFiles('tool/tlrelease')")],
              run := Release.WorkflowPolicy.Run.command { executable := "/usr/bin/false", arguments := [] } },
            { name := "make the validated release tool executable",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "/bin/chmod",
                         arguments := [Release.WorkflowPolicy.Argument.literal "0755",
                                       Release.WorkflowPolicy.Argument.literal "tool/tlrelease"] } },
            { name := "enter the validated release tool",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "--help"] } }],
  references := ["needs.gates.outputs.releaseToolFileSetHash"] },
{ name := "stamp",
  fields := [("if", "github.event_name != 'workflow_dispatch' || !inputs.handoff_only"),
             ("needs", "[gates]"),
             ("outputs",
              "\n      version: ${{ steps.stamp.outputs.version }}\n      commit: ${{ steps.stamp.outputs.commit }}\n      stampDigest: ${{ steps.stamp.outputs.stampDigest }}"),
             ("runs-on", "ubuntu-latest"),
             ("timeout-minutes", "10")],
  closedSteps := true,
  steps := [{ name := "",
              fields := [("uses", "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "a rehearsal is not a release",
              fields := [("if", "github.event_name == 'workflow_dispatch' && github.ref_type == 'tag'")],
              run := Release.WorkflowPolicy.Run.command { executable := "/usr/bin/false", arguments := [] } },
            { name := "download the release tool",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with", "\n          name: release-tool\n          path: tool")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "refuse a missing or changed release tool",
              fields := [("if",
                          "needs.gates.outputs.releaseToolFileSetHash == '' || hashFiles('tool/tlrelease') == '' || needs.gates.outputs.releaseToolFileSetHash != hashFiles('tool/tlrelease')")],
              run := Release.WorkflowPolicy.Run.command { executable := "/usr/bin/false", arguments := [] } },
            { name := "make the validated release tool executable",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "/bin/chmod",
                         arguments := [Release.WorkflowPolicy.Argument.literal "0755",
                                       Release.WorkflowPolicy.Argument.literal "tool/tlrelease"] } },
            { name := "enter the validated release tool",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "--help"] } },
            { name := "validate the release identity",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "identity-check",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json"] } },
            { name := "stamp the tagged commit",
              fields := [("env",
                          "\n          RELEASE_REF_TYPE: ${{ github.ref_type }}\n          RELEASE_REF_NAME: ${{ github.ref_name }}"),
                         ("id", "stamp")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "workflow-stamp",
                                       Release.WorkflowPolicy.Argument.literal "--root",
                                       Release.WorkflowPolicy.Argument.literal ".",
                                       Release.WorkflowPolicy.Argument.literal "--ref-type",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_REF_TYPE",
                                       Release.WorkflowPolicy.Argument.literal "--ref-name",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_REF_NAME",
                                       Release.WorkflowPolicy.Argument.literal "--output",
                                       Release.WorkflowPolicy.Argument.environment "GITHUB_OUTPUT"] } },
            { name := "upload the stamp",
              fields := [("uses", "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"),
                         ("with",
                          "\n          name: tl-build-stamp\n          path: Tl/Build/Stamp.lean\n          if-no-files-found: error\n          retention-days: 1")],
              run := Release.WorkflowPolicy.Run.none }],
  references := ["needs.gates.outputs.releaseToolFileSetHash", "steps.stamp.outputs.commit",
                 "steps.stamp.outputs.stampDigest", "steps.stamp.outputs.version"] },
{ name := "build",
  fields := [("continue-on-error", "${{ matrix.best_effort }}"),
             ("needs", "[gates, stamp]"),
             ("runs-on", "${{ matrix.runs-on }}"),
             ("strategy",
              "\n      fail-fast: false\n      matrix:\n        include:\n          - target: linux-x64\n            runs-on: ubuntu-latest\n            container: true\n            best_effort: false\n            elan_triple: x86_64-unknown-linux-gnu\n            elan_sha256: df0b2b3a439961ffcbb3985214365ffe40f49bc871df04dff268c7d8e21ca8b2\n          - target: linux-arm64\n            runs-on: ubuntu-24.04-arm\n            container: true\n            best_effort: false\n            elan_triple: aarch64-unknown-linux-gnu\n            elan_sha256: cb69af0803b04157bc30201c29c12fca882bb3ad8b43476b8d2d3064810bc3ac\n          - target: darwin-arm64\n            runs-on: macos-15\n            container: false\n            best_effort: false\n          - target: darwin-x64\n            runs-on: macos-15-intel\n            container: false\n            best_effort: true"),
             ("timeout-minutes", "120")],
  closedSteps := false,
  steps := [],
  references := ["needs.stamp.outputs.commit", "needs.stamp.outputs.stampDigest", "needs.stamp.outputs.version"] },
{ name := "sign",
  fields := [("environment", "release"),
             ("if", "github.event_name == 'push' && github.ref_type == 'tag'"),
             ("needs", "[gates, stamp, build]"),
             ("permissions", "\n      contents: read\n      id-token: write\n      attestations: write"),
             ("runs-on", "ubuntu-latest"),
             ("timeout-minutes", "30")],
  closedSteps := true,
  steps := [{ name := "",
              fields := [("uses", "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0"),
                         ("with", "\n          fetch-depth: 0")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "install cosign",
              fields := [("uses", "sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "download the release candidates",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with",
                          "\n          pattern: release-candidate-*\n          merge-multiple: true\n          path: dist")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "download the release tool",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with", "\n          name: release-tool\n          path: tool")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "refuse a missing or changed release tool",
              fields := [("if",
                          "needs.gates.outputs.releaseToolFileSetHash == '' || hashFiles('tool/tlrelease') == '' || needs.gates.outputs.releaseToolFileSetHash != hashFiles('tool/tlrelease')")],
              run := Release.WorkflowPolicy.Run.command { executable := "/usr/bin/false", arguments := [] } },
            { name := "make the validated release tool executable",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "/bin/chmod",
                         arguments := [Release.WorkflowPolicy.Argument.literal "0755",
                                       Release.WorkflowPolicy.Argument.literal "tool/tlrelease"] } },
            { name := "enter the validated release tool",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "--help"] } },
            { name := "validate the release identity",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "identity-check",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json"] } },
            { name := "the checkout, protected main and tag agree",
              fields := [("env",
                          "\n          RELEASE_TAG: ${{ github.ref_name }}\n          RELEASE_COMMIT: ${{ needs.stamp.outputs.commit }}")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "workflow-source",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json",
                                       Release.WorkflowPolicy.Argument.literal "--tag",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_TAG",
                                       Release.WorkflowPolicy.Argument.literal "--commit",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_COMMIT"] } },
            { name := "this job's identity matches the pin",
              fields := [("env", "\n          CERTIFICATE_SAN: https://github.com/${{ github.workflow_ref }}")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "identity-accepts",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json",
                                       Release.WorkflowPolicy.Argument.literal "--san",
                                       Release.WorkflowPolicy.Argument.environment "CERTIFICATE_SAN"] } },
            { name := "the signing pin remains canonical",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "identity-check",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json"] } },
            { name := "the external prerequisites are in place",
              fields := [("env", "\n          GH_TOKEN: ${{ github.token }}")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "prereqs",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json",
                                       Release.WorkflowPolicy.Argument.literal "--plan",
                                       Release.WorkflowPolicy.Argument.literal "release/plan.json"] } },
            { name := "assemble and describe the release",
              fields := [("env",
                          "\n          RELEASE_TAG: ${{ github.ref_name }}\n          RELEASE_COMMIT: ${{ needs.stamp.outputs.commit }}\n          RELEASE_WORKFLOW: ${{ github.workflow_ref }}\n          RELEASE_RUN: ${{ github.run_id }}")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "workflow-prepare",
                                       Release.WorkflowPolicy.Argument.literal "--dist",
                                       Release.WorkflowPolicy.Argument.literal "dist",
                                       Release.WorkflowPolicy.Argument.literal "--tag",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_TAG",
                                       Release.WorkflowPolicy.Argument.literal "--commit",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_COMMIT",
                                       Release.WorkflowPolicy.Argument.literal "--workflow-ref",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_WORKFLOW",
                                       Release.WorkflowPolicy.Argument.literal "--run-id",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_RUN"] } },
            { name := "sign the exact set and emit attestation subjects",
              fields := [("id", "subjects")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "workflow-sign",
                                       Release.WorkflowPolicy.Argument.literal "--dist",
                                       Release.WorkflowPolicy.Argument.literal "dist",
                                       Release.WorkflowPolicy.Argument.literal "--output",
                                       Release.WorkflowPolicy.Argument.environment "GITHUB_OUTPUT"] } },
            { name := "attest build provenance",
              fields := [("uses", "actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8"),
                         ("with", "\n          subject-path: ${{ steps.subjects.outputs.paths }}")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "verify every candidate before handing it off",
              fields := [("env",
                          "\n          RELEASE_TAG: ${{ github.ref_name }}\n          RELEASE_COMMIT: ${{ needs.stamp.outputs.commit }}")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "workflow-verify",
                                       Release.WorkflowPolicy.Argument.literal "--dist",
                                       Release.WorkflowPolicy.Argument.literal "dist",
                                       Release.WorkflowPolicy.Argument.literal "--tag",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_TAG",
                                       Release.WorkflowPolicy.Argument.literal "--commit",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_COMMIT"] } },
            { name := "upload the signed release",
              fields := [("uses", "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"),
                         ("with",
                          "\n          name: tl-signed-release\n          path: dist\n          if-no-files-found: error\n          retention-days: 7")],
              run := Release.WorkflowPolicy.Run.none }],
  references := ["needs.gates.outputs.releaseToolFileSetHash", "needs.stamp.outputs.commit",
                 "steps.subjects.outputs.paths"] },
{ name := "publish-release",
  fields := [("environment", "release"),
             ("if", "github.event_name == 'push' && github.ref_type == 'tag'"),
             ("needs", "[gates, stamp, sign]"),
             ("permissions", "\n      contents: write"),
             ("runs-on", "ubuntu-latest"),
             ("timeout-minutes", "20")],
  closedSteps := true,
  steps := [{ name := "",
              fields := [("uses", "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "install cosign",
              fields := [("uses", "sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "download the signed release",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with", "\n          name: tl-signed-release\n          path: dist")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "download the release tool",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with", "\n          name: release-tool\n          path: tool")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "refuse a missing or changed release tool",
              fields := [("if",
                          "needs.gates.outputs.releaseToolFileSetHash == '' || hashFiles('tool/tlrelease') == '' || needs.gates.outputs.releaseToolFileSetHash != hashFiles('tool/tlrelease')")],
              run := Release.WorkflowPolicy.Run.command { executable := "/usr/bin/false", arguments := [] } },
            { name := "make the validated release tool executable",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "/bin/chmod",
                         arguments := [Release.WorkflowPolicy.Argument.literal "0755",
                                       Release.WorkflowPolicy.Argument.literal "tool/tlrelease"] } },
            { name := "enter the validated release tool",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "--help"] } },
            { name := "validate the release identity",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "identity-check",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json"] } },
            { name := "authenticate, recheck source, and publish the release",
              fields := [("env",
                          "\n          RELEASE_TAG: ${{ github.ref_name }}\n          RELEASE_COMMIT: ${{ needs.stamp.outputs.commit }}\n          GH_TOKEN: ${{ github.token }}")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "workflow-publish",
                                       Release.WorkflowPolicy.Argument.literal "--dist",
                                       Release.WorkflowPolicy.Argument.literal "dist",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json",
                                       Release.WorkflowPolicy.Argument.literal "--tag",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_TAG",
                                       Release.WorkflowPolicy.Argument.literal "--commit",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_COMMIT"] } }],
  references := ["needs.gates.outputs.releaseToolFileSetHash", "needs.stamp.outputs.commit"] },
{ name := "publish-homebrew",
  fields := [("environment", "release"),
             ("if",
              "github.event_name == 'push' && github.ref_type == 'tag' && needs.gates.outputs.homebrew == 'true'"),
             ("needs", "[gates, stamp, publish-release]"),
             ("permissions", "\n      contents: read"),
             ("runs-on", "ubuntu-latest"),
             ("timeout-minutes", "15")],
  closedSteps := true,
  steps := [{ name := "",
              fields := [("uses", "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "install cosign",
              fields := [("uses", "sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "download the signed release",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with", "\n          name: tl-signed-release\n          path: dist")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "download the release tool",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with", "\n          name: release-tool\n          path: tool")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "refuse a missing or changed release tool",
              fields := [("if",
                          "needs.gates.outputs.releaseToolFileSetHash == '' || hashFiles('tool/tlrelease') == '' || needs.gates.outputs.releaseToolFileSetHash != hashFiles('tool/tlrelease')")],
              run := Release.WorkflowPolicy.Run.command { executable := "/usr/bin/false", arguments := [] } },
            { name := "make the validated release tool executable",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "/bin/chmod",
                         arguments := [Release.WorkflowPolicy.Argument.literal "0755",
                                       Release.WorkflowPolicy.Argument.literal "tool/tlrelease"] } },
            { name := "enter the validated release tool",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "--help"] } },
            { name := "validate the release identity",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "identity-check",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json"] } },
            { name := "authenticate, render, and publish the formula",
              fields := [("env",
                          "\n          RELEASE_TAG: ${{ github.ref_name }}\n          RELEASE_COMMIT: ${{ needs.stamp.outputs.commit }}\n          GH_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}\n          HOMEBREW_TAP_SIGNING_KEY: ${{ secrets.HOMEBREW_TAP_SIGNING_KEY }}")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "workflow-homebrew",
                                       Release.WorkflowPolicy.Argument.literal "--dist",
                                       Release.WorkflowPolicy.Argument.literal "dist",
                                       Release.WorkflowPolicy.Argument.literal "--output-dir",
                                       Release.WorkflowPolicy.Argument.literal "out",
                                       Release.WorkflowPolicy.Argument.literal "--signer",
                                       Release.WorkflowPolicy.Argument.literal "release/tap-signer.json",
                                       Release.WorkflowPolicy.Argument.literal "--tag",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_TAG",
                                       Release.WorkflowPolicy.Argument.literal "--commit",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_COMMIT"] } },
            { name := "upload the rendered formula",
              fields := [("uses", "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"),
                         ("with",
                          "\n          name: tl-homebrew-formula\n          path: out/tl.rb\n          if-no-files-found: error")],
              run := Release.WorkflowPolicy.Run.none }],
  references := ["needs.gates.outputs.homebrew", "needs.gates.outputs.releaseToolFileSetHash",
                 "needs.stamp.outputs.commit"] },
{ name := "publish-npm",
  fields := [("environment", "release"),
             ("if", "github.event_name == 'push' && github.ref_type == 'tag' && needs.gates.outputs.npm == 'true'"),
             ("needs", "[gates, stamp, publish-release]"),
             ("permissions", "\n      contents: read\n      id-token: write"),
             ("runs-on", "ubuntu-latest"),
             ("timeout-minutes", "20")],
  closedSteps := true,
  steps := [{ name := "",
              fields := [("uses", "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "install cosign",
              fields := [("uses", "sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "",
              fields := [("uses", "actions/setup-node@820762786026740c76f36085b0efc47a31fe5020"),
                         ("with",
                          "\n          node-version: \"22\"\n          registry-url: \"https://registry.npmjs.org\"")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "install the pinned npm CLI",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "npm",
                         arguments := [Release.WorkflowPolicy.Argument.literal "install",
                                       Release.WorkflowPolicy.Argument.literal "-g",
                                       Release.WorkflowPolicy.Argument.literal "--ignore-scripts",
                                       Release.WorkflowPolicy.Argument.literal "npm@11.5.1"] } },
            { name := "download the signed assets",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with", "\n          name: tl-signed-release\n          path: dist")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "download the release tool",
              fields := [("uses", "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"),
                         ("with", "\n          name: release-tool\n          path: tool")],
              run := Release.WorkflowPolicy.Run.none },
            { name := "refuse a missing or changed release tool",
              fields := [("if",
                          "needs.gates.outputs.releaseToolFileSetHash == '' || hashFiles('tool/tlrelease') == '' || needs.gates.outputs.releaseToolFileSetHash != hashFiles('tool/tlrelease')")],
              run := Release.WorkflowPolicy.Run.command { executable := "/usr/bin/false", arguments := [] } },
            { name := "make the validated release tool executable",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "/bin/chmod",
                         arguments := [Release.WorkflowPolicy.Argument.literal "0755",
                                       Release.WorkflowPolicy.Argument.literal "tool/tlrelease"] } },
            { name := "enter the validated release tool",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "--help"] } },
            { name := "validate the release identity",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "identity-check",
                                       Release.WorkflowPolicy.Argument.literal "--identity",
                                       Release.WorkflowPolicy.Argument.literal "release/identity.json"] } },
            { name := "authenticate the received release",
              fields := [("env",
                          "\n          RELEASE_TAG: ${{ github.ref_name }}\n          RELEASE_COMMIT: ${{ needs.stamp.outputs.commit }}")],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "workflow-verify",
                                       Release.WorkflowPolicy.Argument.literal "--dist",
                                       Release.WorkflowPolicy.Argument.literal "dist",
                                       Release.WorkflowPolicy.Argument.literal "--tag",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_TAG",
                                       Release.WorkflowPolicy.Argument.literal "--commit",
                                       Release.WorkflowPolicy.Argument.environment "RELEASE_COMMIT"] } },
            { name := "stage the npm packages around the signed binaries",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "npm-stage",
                                       Release.WorkflowPolicy.Argument.literal "--root",
                                       Release.WorkflowPolicy.Argument.literal ".",
                                       Release.WorkflowPolicy.Argument.literal "--dist",
                                       Release.WorkflowPolicy.Argument.literal "dist",
                                       Release.WorkflowPolicy.Argument.literal "--manifest",
                                       Release.WorkflowPolicy.Argument.literal "dist/release-manifest.json",
                                       Release.WorkflowPolicy.Argument.literal "--staging",
                                       Release.WorkflowPolicy.Argument.literal "npm-staging"] } },
            { name := "publish",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./tool/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "npm-publish",
                                       Release.WorkflowPolicy.Argument.literal "--staging",
                                       Release.WorkflowPolicy.Argument.literal "npm-staging",
                                       Release.WorkflowPolicy.Argument.literal "--manifest",
                                       Release.WorkflowPolicy.Argument.literal "dist/release-manifest.json"] } }],
  references := ["needs.gates.outputs.npm", "needs.gates.outputs.releaseToolFileSetHash",
                 "needs.stamp.outputs.commit"] }
] }

def ciContract : Contract := {
  header := [("concurrency", "\n  group: ci-${{ github.ref }}\n  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}"),
 ("defaults", "\n  run:\n    shell: bash"),
 ("name", "CI"),
 ("on", "\n  push:\n    branches: ['**']\n  pull_request:\n  workflow_dispatch:"),
 ("permissions", "\n  contents: read")]
  jobs := [
{ name := "release-policy",
  fields := [("runs-on", "ubuntu-latest"), ("timeout-minutes", "20")],
  closedSteps := false,
  steps := [{ name := "release policy",
              fields := [],
              run := Release.WorkflowPolicy.Run.command
                       { executable := "./.lake/build/bin/tlrelease",
                         arguments := [Release.WorkflowPolicy.Argument.literal "policy",
                                       Release.WorkflowPolicy.Argument.literal "--profile",
                                       Release.WorkflowPolicy.Argument.literal "ci",
                                       Release.WorkflowPolicy.Argument.literal "--strict"] } }],
  references := [] },
{ name := "hermetic-release",
  fields := [("runs-on", "ubuntu-latest"), ("timeout-minutes", "20")],
  closedSteps := false,
  steps := [{ name := "build the native hermetic runner",
              fields := [],
              run := .command { executable := "lake", arguments := [
                .literal "build", .literal "tlrelease", .literal "--wfail"] } },
            { name := "runtime-stripped release policy and retained-adapter suites",
              fields := [],
              run := .command { executable := "./.lake/build/bin/tlrelease", arguments := [
                .literal "hermetic", .literal "--root", .literal "."] } }],
  references := [] },
{ name := "homebrew-formula",
  fields := [("runs-on", "macos-latest"), ("timeout-minutes", "20")],
  closedSteps := false,
  steps := [],
  references := [] },
{ name := "build-and-test",
  fields := [("runs-on", "${{ matrix.os }}"),
             ("strategy", "\n      fail-fast: false\n      matrix:\n        os: [ubuntu-latest, macos-latest]"),
             ("timeout-minutes", "90")],
  closedSteps := false,
  steps := [],
  references := ["steps.deps-src.outputs.cache-hit", "steps.elan-cache.outputs.cache-hit",
                 "steps.mathlib-cache.outputs.cache-hit"] },
{ name := "git-floor",
  fields := [("env",
              "\n      GIT_FLOOR_VERSION: \"2.17.1\"\n      GIT_FLOOR_SHA256: \"79136e7aa83abae4d8a25c8111f113d3c5a63aeb5fd93cc72c26d49c6d5ba65e\""),
             ("needs", "build-and-test"),
             ("runs-on", "ubuntu-latest"),
             ("timeout-minutes", "30")],
  closedSteps := false,
  steps := [],
  references := [] }
] }

def command : Command := optionCommand "workflow-policy" "--root <dir>"
  "Refuse undeclared workflow authority, output edges, commands or action inputs."
  ["--root", "."] [{ name := "root", takesValue := true }]
  (fun options => options.required "root")
  (fun root => do
    let mut failures : List String := []
    for (path, contract) in [(".github/workflows/release.yml", releaseContract), (".github/workflows/ci.yml", ciContract)] do
      let text ← ofIO (readTextFile (root ++ "/" ++ path))
      failures := failures ++ (Check.failures (checks text contract)).map (path ++ ": " ++ ·)
    if !failures.isEmpty then decline (String.intercalate "\n" failures)
    return "both workflows match their reviewed authority and invocation schemas")

end Release.WorkflowPolicy
