#!/bin/sh
# Generate the release SBOM, in SPDX 2.3 JSON.
#
#   scripts/gen-sbom.sh <version> <output.spdx.json>
#   scripts/gen-sbom.sh --selftest
#
# ADR-0006 requires every binary release to include an SBOM and the full
# link-time dependency audit. The audit is per-target and produced by the build
# legs (they are the only place the actual binary exists); this is the
# repository-level half — what went into the build, from the files that fix it.
#
# The inputs are the ones that already determine the build, so the SBOM is a
# function of the commit rather than a separately maintained list that could
# disagree with it:
#
#   lean-toolchain       the compiler, and with it the Lean runtime, GMP,
#                        libuv and the rest of the bundled link set
#   lake-manifest.json   every Lake dependency, pinned to an immutable commit
#   THIRD-PARTY-LICENSES the notice file, whose entries are generated from the
#                        same inputs by scripts/GenLicenses.lean
#
# Not generated by a third-party scanner: none of them understands Lake, and a
# scanner that silently found nothing would produce a confident empty SBOM —
# worse than none, because it looks like evidence. This one refuses when an
# input is missing or unparseable.
set -eu

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
repo_root=$(CDPATH='' cd -- "$script_dir/.." && pwd -P)
RC_LIB_SELF="$script_dir/lib/release-common.sh"
# shellcheck source=lib/release-common.sh
. "$RC_LIB_SELF"

usage() {
  echo "usage: $0 <version> <output> | $0 --selftest" >&2
  exit 2
}

generate() {
  version=$1
  output=$2
  ROOT="$repo_root" VERSION="$version" OUTPUT="$output" python3 <<'PYEOF'
import json
import os
import re
import sys

root = os.environ["ROOT"]
version = os.environ["VERSION"]
output = os.environ["OUTPUT"]


def die(message):
    sys.exit(f"gen-sbom: {message}")


SEMVER = re.compile(
    r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"
    r"(-[0-9A-Za-z]+([.-][0-9A-Za-z]+)*)?$"
)
if SEMVER.match(version) is None:
    die(f"'{version}' is not a SemVer version; pass it without a leading 'v'.")


def read(rel):
    try:
        with open(os.path.join(root, rel), encoding="utf-8") as handle:
            return handle.read()
    except FileNotFoundError:
        die(f"{rel} not found. The SBOM is derived from the files that fix the build; without it this document would understate what ships.")


toolchain = read("lean-toolchain").strip()
if not toolchain:
    die("lean-toolchain is empty")
manifest = json.loads(read("lake-manifest.json"))
packages = manifest.get("packages", [])
if not packages:
    die("lake-manifest.json lists no packages, which cannot be right — an empty SBOM would read as 'nothing ships' rather than as a broken generator.")

# SPDX ids must be unique and match [A-Za-z0-9.-]. Package names are already
# in that class, but the mapping is explicit rather than assumed.
def spdx_id(name):
    cleaned = re.sub(r"[^A-Za-z0-9.-]", "-", name)
    return f"SPDXRef-Package-{cleaned}"


relationships = [
    {
        "spdxElementId": "SPDXRef-DOCUMENT",
        "relationshipType": "DESCRIBES",
        "relatedSpdxElement": "SPDXRef-Package-tl",
    }
]
spdx_packages = [
    {
        "SPDXID": "SPDXRef-Package-tl",
        "name": "tl",
        "versionInfo": version,
        "downloadLocation": "https://github.com/DmitryKorolev/tl",
        "filesAnalyzed": False,
        "licenseConcluded": "Apache-2.0",
        "licenseDeclared": "Apache-2.0",
        "copyrightText": "NOASSERTION",
        "supplier": "Organization: DmitryKorolev",
    },
    # The toolchain is a dependency of the artifact in every sense that matters
    # here: it supplies the Lean runtime and, through it, the statically linked
    # GMP that the ADR-0006 licensing section is about.
    {
        "SPDXID": "SPDXRef-Package-lean-toolchain",
        "name": "lean4",
        "versionInfo": toolchain,
        "downloadLocation": "https://github.com/leanprover/lean4",
        "filesAnalyzed": False,
        "licenseConcluded": "Apache-2.0",
        "licenseDeclared": "Apache-2.0",
        "copyrightText": "NOASSERTION",
        "supplier": "Organization: Lean FRO",
        "comment": (
            "Supplies the Lean runtime linked into every tl binary, and with it the "
            "statically linked GMP (LGPL-3.0-or-later, elected over the GPL-2.0 option) "
            "and libuv (MIT). See the licensing section of ADR-0006 and THIRD-PARTY-LICENSES."
        ),
    },
    {
        "SPDXID": "SPDXRef-Package-gmp",
        "name": "gmp",
        "versionInfo": "NOASSERTION",
        "downloadLocation": "https://gmplib.org/",
        "filesAnalyzed": False,
        "licenseConcluded": "LGPL-3.0-or-later",
        "licenseDeclared": "LGPL-3.0-or-later OR GPL-2.0-or-later",
        "copyrightText": "NOASSERTION",
        "supplier": "NOASSERTION",
        "comment": (
            "Statically linked via the Lean toolchain, not vendored by this project. tl "
            "elects the LGPL-3.0 option; the section 4 relink obligation is met by tl "
            "remaining open source with a pinned build system (ADR-0006)."
        ),
    },
    {
        "SPDXID": "SPDXRef-Package-libuv",
        "name": "libuv",
        "versionInfo": "NOASSERTION",
        "downloadLocation": "https://github.com/libuv/libuv",
        "filesAnalyzed": False,
        "licenseConcluded": "MIT",
        "licenseDeclared": "MIT",
        "copyrightText": "NOASSERTION",
        "supplier": "NOASSERTION",
        "comment": (
            "Statically linked into every Lean binary and omitted from Lean's own bundled "
            "LICENSES file, so tl's notice adds the entry itself."
        ),
    },
]
for spdx_package in spdx_packages[1:]:
    relationships.append(
        {
            "spdxElementId": "SPDXRef-Package-tl",
            "relationshipType": "DEPENDS_ON",
            "relatedSpdxElement": spdx_package["SPDXID"],
        }
    )

for package in packages:
    name = package.get("name")
    rev = package.get("rev")
    url = package.get("url", "NOASSERTION")
    if not name or not rev:
        die(
            f"a lake-manifest.json entry has no name or no rev ({package!r}). ADR-0009 pins "
            "every dependency to an immutable commit, so an entry without one is either a "
            "manifest this generator does not understand or a pin that is not immutable."
        )
    identifier = spdx_id(name)
    spdx_packages.append(
        {
            "SPDXID": identifier,
            "name": name,
            "versionInfo": rev,
            "downloadLocation": f"git+{url}@{rev}" if url != "NOASSERTION" else "NOASSERTION",
            "filesAnalyzed": False,
            # The permissive allowlist is enforced by Tests/CliTests.lean against
            # each package's LICENSE on disk; stating a concluded license here
            # without re-deriving it would be a second, weaker copy of that gate.
            "licenseConcluded": "NOASSERTION",
            "licenseDeclared": "NOASSERTION",
            "copyrightText": "NOASSERTION",
            "supplier": "NOASSERTION",
            "comment": (
                "Lake dependency, pinned to an immutable commit (ADR-0009). Its license is "
                "classified fail-closed against the permissive allowlist by Tests/CliTests.lean "
                "and recorded in THIRD-PARTY-LICENSES."
            ),
        }
    )
    relationships.append(
        {
            "spdxElementId": "SPDXRef-Package-tl",
            "relationshipType": "DEPENDS_ON",
            "relatedSpdxElement": identifier,
        }
    )

document = {
    "spdxVersion": "SPDX-2.3",
    "dataLicense": "CC0-1.0",
    "SPDXID": "SPDXRef-DOCUMENT",
    "name": f"tl-{version}",
    # Deliberately derived from the version rather than from a timestamp or a
    # random UUID: this document is regenerated by anyone rebuilding the same
    # release, and a field that changed per run would make two correct SBOMs
    # for one release differ.
    "documentNamespace": f"https://github.com/DmitryKorolev/tl/spdx/v{version}",
    "creationInfo": {
        # No `created` timestamp, for the same reason. SPDX requires the field,
        # so it carries the release rather than the moment of generation.
        "created": "1970-01-01T00:00:00Z",
        "creators": ["Tool: scripts/gen-sbom.sh", "Organization: DmitryKorolev"],
        "comment": (
            "Generated from lean-toolchain and lake-manifest.json, the files that fix this "
            "build. The `created` field is fixed rather than stamped so the document is a "
            "function of the release and two independent generations agree. The per-target "
            "link-time audit ships alongside as link-audit-<target>.txt."
        ),
    },
    "packages": spdx_packages,
    "relationships": relationships,
}

with open(output, "w", encoding="utf-8") as handle:
    json.dump(document, handle, indent=2, sort_keys=True)
    handle.write("\n")
print(f"gen-sbom: wrote {output} — {len(spdx_packages)} packages for tl {version}")
PYEOF
}

selftest() {
  work=$(mktemp -d)
  trap 'rm -rf "$work"' EXIT
  rc_selftest_begin "gen-sbom" "$work"

  out="$work/sbom.spdx.json"
  rc_expect_status 0 "the repository's inputs produce an SBOM" "$0" 1.2.3 "$out"
  rc_note "$(python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$out" 2>/dev/null && echo 0 || echo 1)" \
    "the SBOM is valid JSON"
  for field in spdxVersion dataLicense SPDXID documentNamespace; do
    rc_note "$(grep -q "\"$field\"" "$out" && echo 0 || echo 1)" "it carries $field"
  done
  # The licensing boundary ADR-0006 is about must be in there by name, or the
  # document does not discharge what it is produced for.
  for needle in gmp libuv LGPL-3.0-or-later lean4; do
    rc_note "$(grep -q -- "$needle" "$out" && echo 0 || echo 1)" "it names $needle"
  done
  # Every Lake dependency, counted against the manifest rather than eyeballed.
  want=$(python3 -c 'import json,sys; print(len(json.load(open(sys.argv[1]))["packages"]))' "$repo_root/lake-manifest.json")
  got=$(python3 -c '
import json, sys
doc = json.load(open(sys.argv[1]))
manifest = {p["name"] for p in json.load(open(sys.argv[2]))["packages"]}
print(len([p for p in doc["packages"] if p["name"] in manifest]))' "$out" "$repo_root/lake-manifest.json")
  rc_note "$([ "$got" = "$want" ] && echo 0 || echo 1)" \
    "every lake-manifest package appears ($got of $want)"
  # Each dependency carries its pinned commit, not a branch or a range.
  rc_note "$(python3 -c '
import json, re, sys
doc = json.load(open(sys.argv[1]))
manifest = {p["name"]: p["rev"] for p in json.load(open(sys.argv[2]))["packages"]}
bad = [p["name"] for p in doc["packages"]
       if p["name"] in manifest and p["versionInfo"] != manifest[p["name"]]]
sys.exit(1 if bad else 0)' "$out" "$repo_root/lake-manifest.json" && echo 0 || echo 1)" \
    "each dependency carries the exact revision the manifest pins"

  # Reproducibility: the same inputs must produce the same bytes, or the SBOM
  # cannot be part of a signed set that an independent rebuilder checks.
  out2="$work/sbom2.spdx.json"
  "$0" 1.2.3 "$out2" >/dev/null 2>&1
  rc_note "$([ "$(rc_sha256_of "$out")" = "$(rc_sha256_of "$out2")" ] && echo 0 || echo 1)" \
    "two generations from the same inputs are byte-identical"
  out3="$work/sbom3.spdx.json"
  "$0" 1.2.4 "$out3" >/dev/null 2>&1
  rc_note "$([ "$(rc_sha256_of "$out")" != "$(rc_sha256_of "$out3")" ] && echo 0 || echo 1)" \
    "a different version produces a different document"

  # Refusals. A scanner that silently finds nothing produces a confident empty
  # SBOM, which is worse than none because it looks like evidence.
  rc_expect_output 1 "not a SemVer" "a non-SemVer version is refused" "$0" v1.2.3 "$work/o1"
  rc_expect_status 2 "no arguments is a usage error" "$0"
  rc_expect_status 2 "one argument is a usage error" "$0" 1.2.3
  rc_expect_status 2 "an unknown flag is a usage error" "$0" --bogus

  # A missing or empty input must refuse rather than understate what ships.
  alt="$work/alt"
  mkdir -p "$alt/scripts/lib"
  cp "$0" "$alt/scripts/"
  cp "$RC_LIB_SELF" "$alt/scripts/lib/"
  cp "$repo_root/lake-manifest.json" "$alt/"
  rc_expect_output 1 "lean-toolchain not found" "a missing lean-toolchain is refused" \
    "$alt/scripts/$(basename -- "$0")" 1.2.3 "$work/o2"
  cp "$repo_root/lean-toolchain" "$alt/"
  printf '{"packages": []}\n' > "$alt/lake-manifest.json"
  rc_expect_output 1 "empty SBOM" "a manifest with no packages is refused" \
    "$alt/scripts/$(basename -- "$0")" 1.2.3 "$work/o3"
  printf '{"packages": [{"name": "x"}]}\n' > "$alt/lake-manifest.json"
  rc_expect_output 1 "immutable commit" "a dependency with no pinned revision is refused" \
    "$alt/scripts/$(basename -- "$0")" 1.2.3 "$work/o4"

  rc_selftest_end "An SBOM that understates what ships is worse than none, because it looks like evidence."
}

case "${1-}" in
  '') usage ;;
  --selftest)
    [ "$#" -eq 1 ] || usage
    selftest
    ;;
  -*) usage ;;
  *)
    [ "$#" -eq 2 ] || usage
    generate "$1" "$2"
    ;;
esac
